### PR TITLE
 participants.json

### PR DESCRIPTION
**Pull request by JohnsonAkin**
JohnsonAkin

### CODE REVIEW

**Comment by OSCA-Ado-Ekiti** [comment]
What is your Tech Stack? so i can help you update it.

**Comment by OSCA-Ado-Ekiti** [comment]
Your twitter handle

**Comment by OSCA-Ado-Ekiti** [comment]
> Programming languages

Frontend? Backend? Design?

**Comment by JohnsonAkin** [comment]
Frontend

**Pull request merged**
